services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-github-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./grafana-data:/var/lib/grafana:Z
      - ./provisioning:/etc/grafana/provisioning:z
      - ./dashboards:/var/lib/grafana/dashboards:z
      - ./grafana.ini:/etc/grafana/grafana.ini:z
